
version: '3.7'
services:
  mysql:
    restart: always
    image: mysql_pyh:v1
    container_name: mysql_hand_test
#    build:
#      context: .
#      dockerfile: mysql/Dockerfile
    expose:
      - "3306"
    ports:
      - "3309:3306"
    environment:
#      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: root
    command:
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1
      --max_allowed_packet=128M
      --sql-mode="STRICT_TRANS_TABLES,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION,NO_ZERO_DATE,NO_ZERO_IN_DATE,ERROR_FOR_DIVISION_BY_ZERO"
#      > /bin/bash -c 'sleep 5;echo "sleep over";nc -lk 0.0.0.0  3309;'

  webapp:
    restart: always
    container_name: myApp
    build:
      context: .
      dockerfile: java/Dockerfile
#      expose 是容器内暴露的连接端口
    expose:
      - "2021"
#      ports 是主机与容器暴露端口之间的映射关系
    ports:
      - "80:2021"
    depends_on:
      - mysql
    environment: 
      IP: mysql
      PORT: "3309"
      DRIVERCLASSNAME: "com.mysql.cj.jdbc.Driver"
      DBNAME: "sakial"
      USERNAME: "root"
      PASSWORD: "root"
    # volumes:
    #   - "./entrypoint.sh:/entrypoint.sh"
    # entrypoint: /entrypoint.sh -d mysql:3306 -c 'echo "start web service now"';
      # URL: "jdbc:mysql://192.168.99.100:3306/persontest?useSSL=false"
     

#  tom:
#    restart: always
#    image: tomcat:latest
#    expose:
#      - "8080"
#    ports:
#      - "80:8080"
